### ISSUE TITLE
Incorrect copyright

### ISSUE THREAD

**Issue by IMS212** [DestinyTheGreat/IMSpack#1]
This infringes on my rights, please remove.

**Comment by JustSimplyKyle** [comment]
No it doesn't

**Comment by IMS212** [comment]
damnit

**Comment by JustSimplyKyle** [comment]
no don't close it reopen it

**Comment by JustSimplyKyle** [comment]
the war has not started and you ended it

**Comment by FwuffyPetsOwO** [comment]
There is no war in Ba Sing Se
